# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Vitae"
license = "GPL-2.0"
licenselink = "https://github.com/dataCobra/hugo-vitae/blob/master/LICENSE.md"
description = "Vitae is a blog theme for Hugo that focuses on your content."
homepage = "https://github.com/dataCobra/hugo-vitae"
tags = ["blog", "responsive", "postimage", "clean", "simple", "light", "disqus", "commento", "mobile", "customizable", "minimalistic", "typography", "fontawesome", "reading"]
features = ["responsive", "clean", "disqus", "commento", "postimage", "math", "fontawesome", "social-icons", "customizables", "RSS", "multilingual"]
min_version = "0.62.0"

[author]
  name = "Benedikt 'dataCobra' Tuchen"
  homepage = "https://thinkbot.de"
